replicaCount: 1

image:
  repository: dockaleem/go-web-app 
  pullPolicy: IfNotPresent
  tag: "13871547121"

ingress:
  enabled: false
  className: ""   
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
